name: non-prod
# Define when this workflow should run


on:
  push
# Define the jobs
jobs:
  callPipeline:
    uses: Orisade2003/central-ci-cd/.github/workflows/non-prod.yaml@main
    with:
      app-name: devops-project
      values-path: environments/dev/values/microservice-devops-values.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      GITOPS_REPO_TOKEN: ${{secrets.GITOPS_REPO_TOKEN}}


